version: '3.8'

services:
  server:
    build:
      context: ../../
      dockerfile: packages/server/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://tweeter:tweeter@db:5432/tweeter

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: tweeter
      POSTGRES_PASSWORD: tweeter
      POSTGRES_DB: tweeter
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432" # exposes 5433 for localhost, 5432 for other containers
      
volumes:
  db:
    driver: local