version: '3.8'

services:
  server:
    build:
      context: ../../
      dockerfile: packages/server/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tweeter
      POSTGRES_PASSWORD: tweeter
      POSTGRES_DB: tweeter
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5433:5433"